"""
LLM-generated solution for CGCC (GNN-CB pilot run #3).
Generated by Claude Opus 4.7 under the frozen prompt template (../prompt.md).
Runs on CPU. Writes submission.csv at repo root.
"""

import os, pickle, random, time, math
import numpy as np
import pandas as pd
import networkx as nx
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, accuracy_score
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GINConv, global_mean_pool, global_max_pool

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
device = torch.device("cpu")

DATA = "data"
TRAIN_DIR = f"{DATA}/train"
TEST_DIR = f"{DATA}/test"
LABELS_CSV = f"{DATA}/train_labels.csv"


# ---------- per-graph featurization ----------
def orientation_entropy(G, n_bins=36):
    """Boeing 2019 grid-vs-organic indicator: entropy of compass bearings."""
    bearings = []
    for u, v, _ in G.edges(keys=True) if G.is_multigraph() else G.edges(data=True):
        if not G.is_multigraph():
            v = u[1]; u = u[0]
        try:
            x1, y1 = G.nodes[u]["x"], G.nodes[u]["y"]
            x2, y2 = G.nodes[v]["x"], G.nodes[v]["y"]
        except KeyError:
            continue
        dy, dx = y2 - y1, x2 - x1
        if dx == 0 and dy == 0:
            continue
        ang = math.degrees(math.atan2(dy, dx)) % 180.0  # undirected: fold to [0,180)
        bearings.append(ang)
    if not bearings:
        return 0.0
    h, _ = np.histogram(bearings, bins=n_bins, range=(0.0, 180.0))
    p = h / h.sum() + 1e-12
    H = -(p * np.log(p)).sum()
    return float(H / math.log(n_bins))  # normalized to [0, 1]


def graph_stats(G):
    n = G.number_of_nodes(); m = G.number_of_edges()
    if n == 0:
        return np.zeros(10, dtype=np.float32)
    # collapse multi-edges for clustering / transitivity
    Gs = nx.Graph(G)
    deg = np.array([d for _, d in G.degree()], dtype=np.float32)
    clu = nx.clustering(Gs)
    clu_arr = np.array([clu[n_] for n_ in Gs.nodes()], dtype=np.float32)
    try:
        trans = float(nx.transitivity(Gs))
    except ZeroDivisionError:
        trans = 0.0
    lengths = []
    for _, _, d in (G.edges(data=True) if not G.is_multigraph() else G.edges(keys=False, data=True)):
        if "length" in d:
            lengths.append(float(d["length"]))
    lengths = np.array(lengths, dtype=np.float32) if lengths else np.array([0.0], dtype=np.float32)
    density = (2.0 * m) / max(n * (n - 1), 1)
    return np.array([
        n, m, density,
        deg.mean(), deg.var(),
        clu_arr.mean() if len(clu_arr) else 0.0,
        trans,
        lengths.mean(), (lengths.std() / (lengths.mean() + 1e-6)),
        orientation_entropy(G),
    ], dtype=np.float32)


def build_pyg(G, label=None):
    nodes = list(G.nodes())
    if not nodes:
        return None
    idx = {n: i for i, n in enumerate(nodes)}
    n = len(nodes)

    xs = np.array([G.nodes[n_].get("x", 0.0) for n_ in nodes], dtype=np.float32)
    ys = np.array([G.nodes[n_].get("y", 0.0) for n_ in nodes], dtype=np.float32)
    xs = xs - xs.mean(); ys = ys - ys.mean()
    s = float(np.sqrt(xs.var() + ys.var()) + 1e-6)
    xs /= s; ys /= s

    sc = np.array([float(G.nodes[n_].get("street_count", 0)) for n_ in nodes], dtype=np.float32)
    sc = (sc - sc.mean()) / (sc.std() + 1e-6)

    deg_arr = np.array([G.degree(n_) for n_ in nodes], dtype=np.float32)
    deg_arr = (deg_arr - deg_arr.mean()) / (deg_arr.std() + 1e-6)

    Gs = nx.Graph(G)
    clu = nx.clustering(Gs)
    clu_arr = np.array([clu[n_] for n_ in nodes], dtype=np.float32)

    X = np.stack([xs, ys, sc, deg_arr, clu_arr], axis=1)

    # edges (undirected → both directions)
    e_pairs = []
    for u, v in (G.edges() if not G.is_multigraph() else set((u, v) for u, v in G.edges())):
        if u in idx and v in idx:
            iu, iv = idx[u], idx[v]
            e_pairs.append((iu, iv)); e_pairs.append((iv, iu))
    if not e_pairs:
        e_pairs = [(0, 0)]
    ei = torch.tensor(e_pairs, dtype=torch.long).t()

    stats = graph_stats(G)
    data = Data(x=torch.from_numpy(X), edge_index=ei,
                stats=torch.from_numpy(stats).unsqueeze(0))
    if label is not None:
        data.y = torch.tensor([label], dtype=torch.long)
    return data


# ---------- load all graphs once ----------
print("[load] graphs...")
labels_df = pd.read_csv(LABELS_CSV)
label_map = dict(zip(labels_df["filename"], labels_df["target"]))

train_files = sorted(f for f in os.listdir(TRAIN_DIR) if f.endswith(".pkl"))
test_files = sorted(f for f in os.listdir(TEST_DIR) if f.endswith(".pkl"))


def load_one(path):
    with open(path, "rb") as fh:
        return pickle.load(fh)


train_data, train_labels, train_names = [], [], []
for fn in train_files:
    if fn not in label_map:
        continue
    G = load_one(os.path.join(TRAIN_DIR, fn))
    d = build_pyg(G, label=int(label_map[fn]))
    if d is None:
        continue
    train_data.append(d); train_labels.append(int(label_map[fn])); train_names.append(fn)

test_data, test_names = [], []
for fn in test_files:
    G = load_one(os.path.join(TEST_DIR, fn))
    d = build_pyg(G)
    if d is None:
        continue
    test_data.append(d); test_names.append(fn)

print(f"  train={len(train_data)} test={len(test_data)}")
print(f"  class counts (train): {np.bincount(np.array(train_labels), minlength=3)}")

# stats normalization (fit on train only, apply to all)
all_stats_train = torch.cat([d.stats for d in train_data], dim=0).numpy()
mu = all_stats_train.mean(axis=0); sd = all_stats_train.std(axis=0) + 1e-6
for d in train_data + test_data:
    d.stats = torch.from_numpy(((d.stats.numpy() - mu) / sd).astype(np.float32))


# ---------- model ----------
class GIN_MLP(nn.Module):
    def __init__(self, in_dim, hidden):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden), nn.ReLU(), nn.Linear(hidden, hidden)
        )

    def forward(self, x):
        return self.net(x)


class CGCC_GIN(nn.Module):
    def __init__(self, in_dim=5, n_stats=10, hidden=64, num_classes=3, drop=0.4):
        super().__init__()
        self.conv1 = GINConv(GIN_MLP(in_dim, hidden))
        self.conv2 = GINConv(GIN_MLP(hidden, hidden))
        self.bn1 = nn.BatchNorm1d(hidden); self.bn2 = nn.BatchNorm1d(hidden)
        self.head = nn.Sequential(
            nn.Linear(hidden * 2 + n_stats, hidden), nn.ReLU(), nn.Dropout(drop),
            nn.Linear(hidden, num_classes),
        )

    def forward(self, x, edge_index, batch, stats):
        h = F.relu(self.bn1(self.conv1(x, edge_index)))
        h = F.dropout(h, p=0.3, training=self.training)
        h = F.relu(self.bn2(self.conv2(h, edge_index)))
        gmean = global_mean_pool(h, batch)
        gmax = global_max_pool(h, batch)
        z = torch.cat([gmean, gmax, stats], dim=-1)
        return self.head(z)


# class weights (from full train set)
counts = np.bincount(np.array(train_labels), minlength=3).astype(np.float32)
weights = counts.sum() / (counts + 1e-6)
weights = weights / weights.mean()
class_w = torch.tensor(weights, dtype=torch.float32)
print(f"  class weights: {weights.round(3)}")


def train_one_fold(tr_idx, va_idx, fold):
    tr_set = [train_data[i] for i in tr_idx]
    va_set = [train_data[i] for i in va_idx]
    tr_loader = DataLoader(tr_set, batch_size=8, shuffle=True)
    va_loader = DataLoader(va_set, batch_size=32, shuffle=False)

    model = CGCC_GIN().to(device)
    opt = torch.optim.Adam(model.parameters(), lr=5e-3, weight_decay=1e-3)
    lossf = nn.CrossEntropyLoss(weight=class_w)

    best_f1, best_state, patience, MAX_PAT = -1.0, None, 0, 30
    for epoch in range(200):
        model.train()
        for d in tr_loader:
            d = d.to(device)
            opt.zero_grad()
            logits = model(d.x, d.edge_index, d.batch, d.stats)
            loss = lossf(logits, d.y)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 2.0)
            opt.step()

        model.eval()
        ys, ps = [], []
        with torch.no_grad():
            for d in va_loader:
                d = d.to(device)
                p = model(d.x, d.edge_index, d.batch, d.stats).argmax(-1).cpu().numpy()
                ps.append(p); ys.append(d.y.cpu().numpy())
        yh = np.concatenate(ps); yt = np.concatenate(ys)
        f1 = f1_score(yt, yh, average="macro")
        if f1 > best_f1 + 1e-6:
            best_f1 = f1; patience = 0
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        else:
            patience += 1
            if patience >= MAX_PAT:
                break
    print(f"  fold{fold}: best val_macro_f1 = {best_f1:.4f} (epoch ~{epoch})")
    return best_state, best_f1, va_idx


# ---------- 5-fold CV ----------
print("[cv] 5-fold stratified...")
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
y_arr = np.array(train_labels)
fold_models, fold_scores = [], []
oof_pred = np.zeros((len(train_data), 3), dtype=np.float32)
t0 = time.time()
for fold, (tr_idx, va_idx) in enumerate(skf.split(np.zeros_like(y_arr), y_arr)):
    state, f1, vi = train_one_fold(tr_idx, va_idx, fold)
    fold_models.append(state); fold_scores.append(f1)
    # OOF
    m = CGCC_GIN().to(device); m.load_state_dict(state); m.eval()
    va_loader = DataLoader([train_data[i] for i in vi], batch_size=32, shuffle=False)
    rows = []
    with torch.no_grad():
        for d in va_loader:
            d = d.to(device)
            rows.append(F.softmax(m(d.x, d.edge_index, d.batch, d.stats), dim=-1).cpu().numpy())
    oof_pred[vi] = np.concatenate(rows, axis=0)

cv_mean = float(np.mean(fold_scores)); cv_std = float(np.std(fold_scores))
oof_pred_cls = oof_pred.argmax(-1)
oof_macro_f1 = f1_score(y_arr, oof_pred_cls, average="macro")
oof_acc = accuracy_score(y_arr, oof_pred_cls)
print(f"[cv] mean fold val_macro_f1 = {cv_mean:.4f} ± {cv_std:.4f}"
      f"  ({time.time() - t0:.1f}s)")
print(f"[cv] OOF Macro-F1 = {oof_macro_f1:.4f}, OOF Acc = {oof_acc:.4f}")

# ---------- inference: soft-vote ensemble of 5 fold models ----------
test_loader = DataLoader(test_data, batch_size=32, shuffle=False)
test_softmax_sum = None
for state in fold_models:
    m = CGCC_GIN().to(device); m.load_state_dict(state); m.eval()
    rows = []
    with torch.no_grad():
        for d in test_loader:
            d = d.to(device)
            rows.append(F.softmax(m(d.x, d.edge_index, d.batch, d.stats), dim=-1).cpu().numpy())
    p = np.concatenate(rows, axis=0)
    test_softmax_sum = p if test_softmax_sum is None else test_softmax_sum + p
test_softmax_avg = test_softmax_sum / len(fold_models)
test_pred = test_softmax_avg.argmax(-1)

# ---------- write submission ----------
sub = pd.DataFrame({"filename": test_names, "prediction": test_pred.astype(int)})
sub = sub.sort_values("filename").reset_index(drop=True)
sub.to_csv("submission.csv", index=False)

# self-check
assert set(sub["filename"]) == set(test_files), "filename set mismatch with data/test"
assert sub["prediction"].isin([0, 1, 2]).all(), "predictions out of {0,1,2}"
print(f"[write] submission.csv  ({len(sub)} rows)")

# persist summary
pd.DataFrame([{
    "cv_macro_f1_mean": cv_mean, "cv_macro_f1_std": cv_std,
    "oof_macro_f1": oof_macro_f1, "oof_acc": oof_acc,
    "n_train": len(train_data), "n_test": len(test_data),
    "elapsed_s": time.time() - t0,
}]).to_csv("run_summary.csv", index=False)
