"""
LLM-generated solution for NetLinkArena (GNN-CB pilot run #2).
Generated by Claude Opus 4.7 under the frozen prompt template (../prompt.md).
Runs on CPU. Writes predictions.csv at repo root.
"""

import os
import random
import time
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score, average_precision_score
from torch_geometric.nn import SAGEConv

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
device = torch.device("cpu")

DATA = "data/public"


# ---------- load ----------
print("[load] node_features...")
feat_df = pd.read_csv(f"{DATA}/node_features.csv")
feat_df = feat_df.sort_values("node_id").reset_index(drop=True)
X = feat_df.drop(columns=["node_id"]).values.astype(np.float32)        # (3327, 2742)
# L2 row-normalize (sparse bag-of-words)
norms = np.linalg.norm(X, axis=1, keepdims=True)
norms[norms == 0] = 1.0
X = X / norms
x = torch.from_numpy(X)
N, F_DIM = X.shape
print(f"  features: {X.shape}")

train_e = pd.read_csv(f"{DATA}/train_edges.csv")
val_e = pd.read_csv(f"{DATA}/val_edges.csv")
test_e = pd.read_csv(f"{DATA}/test_nodes.csv")
print(f"  train_edges={len(train_e)}  val_edges={len(val_e)}  test_edges={len(test_e)}")

# message-passing graph from positive train edges only, made undirected
pos_train = train_e[train_e["label"] == 1][["source", "target"]].values.T  # (2, P)
ei_undirected = np.concatenate([pos_train, pos_train[::-1]], axis=1)
edge_index = torch.from_numpy(ei_undirected.astype(np.int64))
print(f"  message-passing edges (undirected): {edge_index.shape[1]}")

# supervision tensors
def to_tensor(df):
    src = torch.tensor(df["source"].values, dtype=torch.long)
    tgt = torch.tensor(df["target"].values, dtype=torch.long)
    if "label" in df.columns:
        y = torch.tensor(df["label"].values, dtype=torch.float)
    else:
        y = None
    return src, tgt, y

train_s, train_t, train_y = to_tensor(train_e)
val_s, val_t, val_y = to_tensor(val_e)
test_s, test_t, _ = to_tensor(test_e)


# ---------- model ----------
class LinkSAGE(nn.Module):
    def __init__(self, in_dim, hidden=128, drop=0.3):
        super().__init__()
        self.conv1 = SAGEConv(in_dim, hidden, aggr="mean")
        self.conv2 = SAGEConv(hidden, hidden, aggr="mean")
        self.drop = drop

    def encode(self, x, edge_index):
        h = F.relu(self.conv1(x, edge_index))
        h = F.dropout(h, p=self.drop, training=self.training)
        h = self.conv2(h, edge_index)
        return h

    def decode(self, z, src, tgt):
        return (z[src] * z[tgt]).sum(dim=-1)


model = LinkSAGE(in_dim=F_DIM).to(device)
opt = torch.optim.Adam(model.parameters(), lr=5e-3, weight_decay=5e-4)
lossf = nn.BCEWithLogitsLoss()


@torch.no_grad()
def evaluate(src, tgt, y):
    model.eval()
    z = model.encode(x, edge_index)
    logits = model.decode(z, src, tgt)
    p = torch.sigmoid(logits).cpu().numpy()
    if y is None:
        return p, None, None
    yt = y.cpu().numpy()
    return p, roc_auc_score(yt, p), average_precision_score(yt, p)


# ---------- train ----------
print("[train]")
best_auc, best_state, patience, MAX_PAT = -1.0, None, 0, 20
t0 = time.time()
for epoch in range(200):
    model.train()
    opt.zero_grad()
    z = model.encode(x, edge_index)
    logits = model.decode(z, train_s, train_t)
    loss = lossf(logits, train_y)
    loss.backward()
    opt.step()

    if epoch % 5 == 0 or epoch < 10:
        _, val_auc, val_ap = evaluate(val_s, val_t, val_y)
        marker = ""
        if val_auc > best_auc:
            best_auc, patience = val_auc, 0
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            marker = "  *"
        else:
            patience += 1
        print(f"  ep{epoch:03d}  loss={loss.item():.4f}  val_auc={val_auc:.4f}  val_ap={val_ap:.4f}{marker}")
        if patience >= MAX_PAT:
            print(f"  early stop at epoch {epoch}")
            break

model.load_state_dict(best_state)
elapsed = time.time() - t0
print(f"[done] best val_auc={best_auc:.4f}  ({elapsed:.1f}s)")

# final val metrics (with best model)
_, final_val_auc, final_val_ap = evaluate(val_s, val_t, val_y)

# ---------- predict test ----------
test_p, _, _ = evaluate(test_s, test_t, None)
sub = pd.DataFrame({"id": test_e["id"].values, "y_pred": test_p})
sub.to_csv("predictions.csv", index=False)

# self-check
ref = pd.read_csv(f"{DATA}/test_nodes.csv")
assert len(sub) == len(ref) == 1822, f"row count mismatch: {len(sub)} vs {len(ref)}"
assert set(sub["id"]) == set(ref["id"]), "id-set mismatch with test_nodes.csv"
assert sub["y_pred"].isna().sum() == 0, "predictions contain NaN"
assert ((sub["y_pred"] >= 0) & (sub["y_pred"] <= 1)).all(), "predictions out of [0,1]"
print(f"[write] predictions.csv  ({len(sub)} rows, {sub['y_pred'].min():.3f}..{sub['y_pred'].max():.3f})")

# also persist a small summary for results.md
pd.DataFrame([{
    "val_auc": final_val_auc, "val_ap": final_val_ap,
    "epochs_run": epoch + 1, "elapsed_s": elapsed,
    "n_train_pairs": len(train_e), "n_val_pairs": len(val_e),
    "n_test_pairs": len(test_e), "mp_edges_undirected": int(edge_index.shape[1]),
}]).to_csv("run_summary.csv", index=False)
