"""
LLM-generated solution for C03 Real_Or_Fake (GNN-CB pilot).
Generated by Claude under the frozen prompt template (see ../prompt.md).
Runs on CPU. Writes submissions/sample_submission/predictions.csv.
"""

import os
import random
import time
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from scipy.sparse import csr_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score, accuracy_score
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import SAGEConv, global_mean_pool, global_max_pool

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
device = torch.device("cpu")

DATA = "data/public"


# ---------- load features ----------
def load_npz_sparse(path):
    f = np.load(path)
    sp = csr_matrix((f["data"], f["indices"], f["indptr"]), shape=tuple(f["shape"]))
    return sp.toarray().astype(np.float32)

print("[load] features...")
bert = load_npz_sparse(f"{DATA}/new_bert_feature.npz")          # (N, 768)
spacy = load_npz_sparse(f"{DATA}/new_spacy_feature.npz")        # (N, 300)
profile = load_npz_sparse(f"{DATA}/new_profile_feature.npz")    # (N, 10)
print("  bert", bert.shape, "spacy", spacy.shape, "profile", profile.shape)

# log1p + standard-scale the profile features (fit on training nodes only)
node_graph_id = np.load(f"{DATA}/node_graph_id.npy")
train_g = np.load(f"{DATA}/train_idx.npy")
train_node_mask = np.isin(node_graph_id, train_g)

profile_log = np.log1p(np.abs(profile)) * np.sign(profile)
scaler = StandardScaler().fit(profile_log[train_node_mask])
profile_scaled = scaler.transform(profile_log).astype(np.float32)

X = np.concatenate([bert, spacy, profile_scaled], axis=1).astype(np.float32)  # (N, 1078)
node_features = torch.from_numpy(X)
print("  combined node features:", X.shape)

# ---------- load graph structure ----------
edges = np.loadtxt(f"{DATA}/A.txt", delimiter=",", dtype=np.int64)             # (E, 2)
val_g = np.load(f"{DATA}/val_idx.npy")
test_g = np.load(f"{DATA}/test_idx.npy")
train_lbl = pd.read_csv(f"{DATA}/train_labels.csv")
val_lbl = pd.read_csv(f"{DATA}/val_labels.csv")
label_map = dict(zip(train_lbl.id, train_lbl.y_true))
label_map.update(dict(zip(val_lbl.id, val_lbl.y_true)))

# group edges and node-ids by graph_id for O(N) graph construction
print("[build] grouping nodes/edges by graph...")
order = np.argsort(node_graph_id, kind="stable")
sorted_gid = node_graph_id[order]
boundaries = np.concatenate(([0], np.where(np.diff(sorted_gid) != 0)[0] + 1, [len(sorted_gid)]))
gid_to_nodes = {sorted_gid[boundaries[i]]: order[boundaries[i]:boundaries[i+1]]
                for i in range(len(boundaries) - 1)}

# precompute global node -> graph map already in node_graph_id; group edges by source graph
edge_gid = node_graph_id[edges[:, 0]]
order_e = np.argsort(edge_gid, kind="stable")
edges_sorted = edges[order_e]
edge_gid_sorted = edge_gid[order_e]
eb = np.concatenate(([0], np.where(np.diff(edge_gid_sorted) != 0)[0] + 1, [len(edge_gid_sorted)]))
gid_to_edges = {edge_gid_sorted[eb[i]]: edges_sorted[eb[i]:eb[i+1]]
                for i in range(len(eb) - 1)}


def build_pyg(g_id, has_label):
    nodes = gid_to_nodes[g_id]
    local = {n: i for i, n in enumerate(nodes)}
    if g_id in gid_to_edges:
        e = gid_to_edges[g_id]
        # filter to intra-graph edges (target also in this graph)
        tgt_gid = node_graph_id[e[:, 1]]
        e = e[tgt_gid == g_id]
        if len(e):
            ei = np.array([[local[u] for u in e[:, 0]],
                           [local[v] for v in e[:, 1]]], dtype=np.int64)
        else:
            ei = np.zeros((2, 0), dtype=np.int64)
    else:
        ei = np.zeros((2, 0), dtype=np.int64)
    x = node_features[nodes]
    data = Data(x=x, edge_index=torch.from_numpy(ei))
    data.graph_id = torch.tensor([g_id], dtype=torch.long)
    if has_label:
        data.y = torch.tensor([label_map[g_id]], dtype=torch.float)
    return data


print("[build] PyG datasets...")
t0 = time.time()
train_set = [build_pyg(g, True) for g in train_g]
val_set = [build_pyg(g, True) for g in val_g]
test_set = [build_pyg(g, False) for g in test_g]
print(f"  train={len(train_set)} val={len(val_set)} test={len(test_set)}"
      f"  ({time.time() - t0:.1f}s)")


# ---------- model ----------
class FakeNewsGNN(nn.Module):
    def __init__(self, in_dim, hidden=128, drop=0.3):
        super().__init__()
        self.conv1 = SAGEConv(in_dim, hidden, aggr="mean")
        self.conv2 = SAGEConv(hidden, hidden, aggr="mean")
        self.root_mlp = nn.Sequential(nn.Linear(in_dim, hidden), nn.ReLU(),
                                      nn.Dropout(drop))
        self.head = nn.Sequential(
            nn.Linear(hidden * 3, hidden), nn.ReLU(), nn.Dropout(drop),
            nn.Linear(hidden, 1),
        )

    def forward(self, x, edge_index, batch):
        h = F.relu(self.conv1(x, edge_index))
        h = F.dropout(h, p=0.3, training=self.training)
        h = F.relu(self.conv2(h, edge_index))
        gmean = global_mean_pool(h, batch)
        gmax = global_max_pool(h, batch)
        # root = first node of each graph (PyG Batch keeps original order)
        roots = torch.zeros(batch.max().item() + 1, dtype=torch.long)
        seen = torch.zeros_like(roots, dtype=torch.bool)
        for i, b in enumerate(batch.tolist()):
            if not seen[b]:
                roots[b] = i; seen[b] = True
        news = self.root_mlp(x[roots])
        return self.head(torch.cat([gmean, gmax, news], dim=-1)).view(-1)


model = FakeNewsGNN(in_dim=X.shape[1]).to(device)
opt = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
lossf = nn.BCEWithLogitsLoss()
train_loader = DataLoader(train_set, batch_size=64, shuffle=True)
val_loader = DataLoader(val_set, batch_size=128, shuffle=False)
test_loader = DataLoader(test_set, batch_size=128, shuffle=False)


def eval_loader(loader):
    model.eval()
    ys, ps = [], []
    with torch.no_grad():
        for d in loader:
            d = d.to(device)
            p = torch.sigmoid(model(d.x, d.edge_index, d.batch)).cpu().numpy()
            ps.append(p)
            if hasattr(d, "y") and d.y is not None:
                ys.append(d.y.cpu().numpy())
    p = np.concatenate(ps)
    y = np.concatenate(ys) if ys else None
    return p, y


# ---------- train ----------
print("[train]")
best_f1, best_state, patience, MAX_PAT = -1.0, None, 0, 5
for epoch in range(30):
    model.train()
    tl = 0.0
    for d in train_loader:
        d = d.to(device)
        opt.zero_grad()
        out = model(d.x, d.edge_index, d.batch)
        loss = lossf(out, d.y)
        loss.backward()
        opt.step()
        tl += float(loss) * d.num_graphs
    tl /= len(train_set)
    p, y = eval_loader(val_loader)
    f1 = f1_score(y.astype(int), (p >= 0.5).astype(int))
    acc = accuracy_score(y.astype(int), (p >= 0.5).astype(int))
    print(f"  ep{epoch:02d}  loss={tl:.4f}  val_f1={f1:.4f}  val_acc={acc:.4f}")
    if f1 > best_f1:
        best_f1, best_state, patience = f1, {k: v.cpu().clone()
                                             for k, v in model.state_dict().items()}, 0
    else:
        patience += 1
        if patience >= MAX_PAT:
            print(f"  early stop at epoch {epoch}")
            break

model.load_state_dict(best_state)

# ---------- threshold tuning on val ----------
val_p, val_y = eval_loader(val_loader)
best_t, best_tf1 = 0.5, -1.0
for t in np.arange(0.30, 0.71, 0.01):
    f1 = f1_score(val_y.astype(int), (val_p >= t).astype(int))
    if f1 > best_tf1:
        best_tf1, best_t = f1, t
val_acc = accuracy_score(val_y.astype(int), (val_p >= best_t).astype(int))
print(f"[tune] best_threshold={best_t:.2f}  val_f1={best_tf1:.4f}  val_acc={val_acc:.4f}")

# ---------- predict test ----------
test_p, _ = eval_loader(test_loader)
test_pred = (test_p >= best_t).astype(int)
test_ids = [int(d.graph_id.item()) for d in test_set]

os.makedirs("submissions/sample_submission", exist_ok=True)
out_path = "submissions/sample_submission/predictions.csv"
pd.DataFrame({"id": test_ids, "y_pred": test_pred}).to_csv(out_path, index=False)

# self-check vs test_idx.csv
ref = pd.read_csv(f"{DATA}/test_idx.csv")
assert set(ref["id"]) == set(test_ids), "id-set mismatch with test_idx.csv"
print(f"[done] wrote {out_path}  ({len(test_ids)} rows)  val_f1={best_tf1:.4f}")

# also persist a small summary for results.md
pd.DataFrame([{
    "val_f1": best_tf1, "val_acc": val_acc,
    "threshold": best_t, "epochs_run": epoch + 1,
    "n_train": len(train_set), "n_val": len(val_set), "n_test": len(test_set),
}]).to_csv("run_summary.csv", index=False)
